
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Checkout
        run: echo step one checkout

      - uses: actions/setup-java@v4.4.0
      - name: Setup JDK
        run: echo setting up jdk

      - uses: ./gradlew build
      - name: Build gradle
        run: echo build gradle

      - uses: actions/upload-artifact@v3.2.1-node20
      - name: Upload a build artifact
        run: echo Uploading artifact
        with:
          name: RoboList.apk
          path: app/build/outputs/apk/app-debug.apk


#      # Runs a set of commands using the runners shell
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
